# Generated by Django 4.0.5 on 2022-07-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'Full-length'), (2, 'EP/Mini-albums'), (3, 'Compilation'), (4, 'Single'), (5, 'Mixtape'), (6, 'DJ Mix'), (7, 'Bootleg/Unauthorized'), (8, 'Live album'), (9, 'Video'), (10, 'Soundtrack'), (11, 'Promo')])),
                ('release_date', models.DateField()),
                ('catalog_id', models.CharField(max_length=16)),
                ('format', models.IntegerField(choices=[(1, 'CD'), (2, 'vinyl'), (3, 'cassette'), (4, 'CD/DVD'), (5, 'digibook'), (6, 'digital'), (7, 'all formats')])),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'on hold'), (3, 'split-up'), (4, 'unknown'), (5, 'changed name'), (6, 'disputed')])),
                ('formed_in', models.IntegerField()),
                ('ended_in', models.IntegerField(null=True)),
                ('lyrical_themes', models.CharField(max_length=60)),
                ('bio', models.TextField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('born', models.DateField(null=True)),
                ('died', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('bio', models.TextField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.album')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(null=True)),
                ('year_to', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=50)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.band')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'closed'), (3, 'unknown')])),
                ('styles', models.CharField(max_length=128)),
                ('founding_year', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='current_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_label', to='music_app.label'),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music_app.genre'),
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(through='music_app.MusicianBand', to='music_app.musician'),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_by', to='music_app.band'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='music_app.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.label'),
        ),
    ]
