# Generated by Django 4.0.5 on 2022-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music_app.genre'),
        ),
    ]
