# Generated by Django 4.0.5 on 2022-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianband',
            name='year_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='musicianband',
            name='year_to',
            field=models.IntegerField(null=True),
        ),
    ]
