# Generated by Django 4.0.5 on 2022-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
